name: CI/CD Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest

      - name: Write SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > ./deploy_key
          chmod 600 ./deploy_key

      - name: Deploy to EC2 (SSH)
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ./deploy_key ubuntu@${EC2_HOST} << 'EOF'
            docker pull ${DOCKER_USER}/myapp:latest
            docker stop myapp || true
            docker rm myapp || true
            docker run -d -p 8080:8080 --name myapp ${DOCKER_USER}/myapp:latest
          EOF
