name: Deploy to EC2

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 소스 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Docker 이미지 빌드 & 푸시
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest

      # 4. EC2에 배포
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker compose -f ~/docker-compose.yml pull
            docker compose -f ~/docker-compose.yml up -d
            # 기존 컨테이너 중지/삭제
            #docker ps -q --filter "name=myapp" | grep -q . && docker stop myapp && docker rm myapp || true
            #docker pull ${{ secrets.DOCKER_USERNAME }}/myapp:latest
            #docker compose up -d -p 8080:8080 --name myapp ${{ secrets.DOCKER_USERNAME }}/myapp:latest
